apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-reg-webapp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: student-reg-webapp
  template:
    metadata:
      labels:
        app: student-reg-webapp
    spec:
      containers:
      - name: student-reg-webapp
        image: 545587708147.dkr.ecr.eu-north-1.amazonaws.com/student-reg-webapp:IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /student-reg-webapp/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /student-reg-webapp/
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5  
